---
# Example .vibe/config.yaml
#
# This file demonstrates how to configure which workflows are available
# in your project. Place this file at .vibe/config.yaml in your project root.

# Simple allowlist of enabled workflows
enabled_workflows:
  - greenfield
  - epcc
  - bugfix
  - my-tdd # Custom TDD workflow from the .vibe/workflows directory

# Available predefined workflows:
# You can retrieve the full list by asking your agent to "list available workflows including the unloaded ones")

# Notes:
# - If no config file exists, all workflows are available (backward compatibility)
# - Empty enabled_workflows array will cause startup to fail
# - Invalid workflow names will cause startup to fail
# - Custom workflows can be loaded from the .vibe/workflows directory
