name: Pull Request Validation

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.2

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install platform-specific dependencies
        run: |
          # Install oxlint platform dependency for Linux (temporary, not saved to package.json)
          pnpm add @oxlint/linux-x64-gnu --save-dev || echo "Failed to install oxlint platform dependency, continuing..."

      - name: Check formatting
        run: pnpm run format:check

      - name: Run linting
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 'latest']

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install platform-specific dependencies
        run: |
          # Install Rollup platform dependency for Linux (temporary, not saved to package.json)
          pnpm add @rollup/rollup-linux-x64-gnu --save-dev || echo "Failed to install Rollup platform dependency, continuing..."

      - name: Build project (CI - skip visualizer)
        run: pnpm run build

      - name: Run tests
        run: pnpm test
        env:
          INCLUDE_NOISY_TESTS: true
          LOG_LEVEL: ERROR
